<?php

namespace Container5IEQoaE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getShippingMethodCalculatorExistsValidatorService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'Sylius\Bundle\ShippingBundle\Validator\ShippingMethodCalculatorExistsValidator' shared service.
     *
     * @return \Sylius\Bundle\ShippingBundle\Validator\ShippingMethodCalculatorExistsValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidator.php';
        include_once \dirname(__DIR__, 4).'/src/Sylius/Bundle/ShippingBundle/Validator/ShippingMethodCalculatorExistsValidator.php';

        return $container->services['Sylius\\Bundle\\ShippingBundle\\Validator\\ShippingMethodCalculatorExistsValidator'] = new \Sylius\Bundle\ShippingBundle\Validator\ShippingMethodCalculatorExistsValidator($container->parameters['sylius.shipping_calculators']);
    }
}
