<?php

namespace ContainerNytzCg0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGatewayFactoryExistsValidatorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Sylius\Bundle\PayumBundle\Validator\GatewayFactoryExistsValidator' shared service.
     *
     * @return \Sylius\Bundle\PayumBundle\Validator\GatewayFactoryExistsValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidator.php';
        include_once \dirname(__DIR__, 4).'/src/Sylius/Bundle/PayumBundle/Validator/GatewayFactoryExistsValidator.php';

        return $container->services['Sylius\\Bundle\\PayumBundle\\Validator\\GatewayFactoryExistsValidator'] = new \Sylius\Bundle\PayumBundle\Validator\GatewayFactoryExistsValidator($container->parameters['sylius.gateway_factories']);
    }
}
